chore: fix python3-tk

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -14,7 +14,7 @@ jobs:
     - name: Install dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install -y g++ python3 python3-pip
+        sudo apt-get install -y g++ python3 python3-pip python3-tk
         python3 -m pip install auto-py-to-exe pyinstaller
 
     - name: Build C++ files
@@ -47,7 +47,10 @@ jobs:
           filename=$(basename "$file" .py)
 
           # Use auto-py-to-exe to create executable
-          python3 -m auto_py_to_exe --onefile --console --name "$filename" --output-dir "build/$dir" "$file"
+          if ! python3 -m auto_py_to_exe --onefile --console --name "$filename" --output-dir "build/$dir" "$file" ; then
+            echo "Failed to build $file"
+            python3 -m auto_py_to_exe --onefile --console --name "$filename" --output-dir "build/$dir" "$file" 2>&1 | tee -a build_errors.log
+          fi
         done
 
     - name: Push build results to another branch
